
CREATE DATABASE IF NOT EXISTS secure_hostel_db;
USE secure_hostel_db;

CREATE TABLE IF NOT EXISTS Users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255),
    Role ENUM('Student', 'Staff', 'HOD', 'Warden', 'Security', 'Admin') NOT NULL,
    GoogleID VARCHAR(255) UNIQUE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Students (
    UserID INT PRIMARY KEY,
    RegisterNumber VARCHAR(50) UNIQUE NOT NULL,
    Block VARCHAR(50) NOT NULL,
    RoomNumber VARCHAR(50) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS GatePassRequests (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    StudentID INT NOT NULL,
    Destination VARCHAR(255) NOT NULL,
    Reason TEXT NOT NULL,
    OutTime DATETIME NOT NULL,
    ExpectedReturnTime DATETIME NOT NULL,
    Status ENUM('Pending', 'StaffApproved', 'HODApproved', 'Rejected') DEFAULT 'Pending',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (StudentID) REFERENCES Students(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS GatePasses (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RequestID INT NOT NULL UNIQUE,
    QRCodeHash VARCHAR(255) UNIQUE NOT NULL,
    IssuedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RequestID) REFERENCES GatePassRequests(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SecurityLogs (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GatePassID INT NOT NULL,
    Action ENUM('Exit', 'Entry') NOT NULL,
    ScannedBy INT NOT NULL,
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (GatePassID) REFERENCES GatePasses(ID) ON DELETE CASCADE,
    FOREIGN KEY (ScannedBy) REFERENCES Users(ID)
);
